all:	malloc_demo.c malloc_demo1.c double_free1.c
	gcc -lm -g -o malloc_demo malloc_demo.c
	gcc -lm -g -o malloc_demo1 malloc_demo1.c
	gcc -lm -g -o double_free1 double_free1.c
	gcc -lm -g -o malloc_mmap_addr malloc_mmap_addr.c
