all:	demo1_overrun.c demo2_overrun.c demo3_use_freed_chunk.c
	gcc -lm -g -o demo1_overrun demo1_overrun.c
	gcc -lm -g -o demo2_overrun demo2_overrun.c
	gcc -lm -g -o demo3_use_freed_chunk demo3_use_freed_chunk.c
